name: MERN CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install backend dependencies
        run: npm ci
        working-directory: ./backend

      #- name: Lint backend
      #  run: npx eslint .
      #  working-directory: ./backend

      - name: Run backend tests
        run: npm test
        working-directory: ./backend

  frontend:
    runs-on: ubuntu-latest
    # needs: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./frontend

     # - name: Lint frontend
     #   run: npx eslint .
     #   working-directory: ./frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

  docker:
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build backend Docker image
        run: docker build -t backend-image ./backend

      - name: Build frontend Docker image
        run: docker build -t frontend-image ./frontend

      - name: List Docker images
        run: docker images
