name: Test Workflow

#on: [push]

on:
    workflow_dispatch:

jobs:
  success-inline-bash:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "GitHub Actions works!"

  success-inline-python:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: |
          print("GitHub Actions works!")
        shell: python

  success-action:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        uses: devops-ammar/GitHub-Actions-Testing@v1
        with:
          message: "GitHub Actions works!"
